# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: "3"

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  web:
    image: public.ecr.aws/i8a0p2p6/example-storefront:latest
    environment:
      - CANONICAL_URL=http://localhost:4000
      - BUILD_GRAPHQL_URL=http://54.216.64.182:3000/graphql
      - EXTERNAL_GRAPHQL_URL=http://54.216.64.182:3000/graphql
      - INTERNAL_GRAPHQL_URL=http://54.216.64.182:3000/graphql
      - PORT=4000
      - SEGMENT_ANALYTICS_SKIP_MINIMIZE=true
      - SEGMENT_ANALYTICS_WRITE_KEY=ENTER_KEY_HERE
      - SESSION_MAX_AGE_MS=2592000000
      - SESSION_SECRET=CHANGEME
      - STRIPE_PUBLIC_API_KEY=ENTER_STRIPE_PUBLIC_KEY_HERE
    networks:
      default:
      reaction:
    ports:
      - 4000:4000
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-web-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-web


