version: '3'

services:
  web:
    image: reactioncommerce/example-storefront:4.0.2
    depends_on:
      - api
      - mongo
    env_file:
      - ./web.env
    networks:
      default:
      reaction:
    ports:
      - 4000:4000
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-web-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-web

  reaction-admin:
    image: reactioncommerce/admin:3.0.0-beta.13
    depends_on:
      - api
      - mongo
    env_file:
      - ./reaction-admin.env
    networks:
      default:
      reaction:
    ports:
      - "80:80"
      - "4080:4080"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-admin-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-admin

  api:
    image: reactioncommerce/reaction:3.11.1
    depends_on:
      - mongo
    env_file:
      - ./reaction-api.env
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-api-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-api

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db
    healthcheck: # re-run rs.initiate() after startup if it failed.
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-mongo-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-mongo

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    depends_on:
      - postgres
    networks:
      default:
      reaction:
    env_file: "hydra-migrate.env"
    restart: on-failure
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-hydra-migrate-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-hydra-migrate
    
  hydra:
    image: oryd/hydra:v1.0.8
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
      - postgres
    networks:
      default:
      reaction:
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    env_file: "hydra-migrate.env"
    restart: unless-stopped
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-hydra-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-hydra

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    networks:
      default:
      reaction:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-postgres-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-postgres

  identity:
    image: reactioncommerce/identity:3.3.0
    depends_on:
      - hydra-migrate
      - hydra
      - mongo
    env_file:
      - ./reaction-identity.env
    networks:
      default:
      reaction:
    ports:
      - "4100:4100"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-identity-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-identity

volumes:
  mongo-db4:
  postgres-data:
