version: '3'

services:
  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    environment:
      - DSN=postgres://hydra:changeme@3.249.242.239:5432/hydra?sslmode=disable
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=true
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=thisisallmyfault
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=http://localhost:4080
      - SERVE_PUBLIC_CORS_ENABLED=true
      - URLS_CONSENT=http://localhost:4100/consent
      - URLS_ERROR=http://localhost:4100/account/oauth-error
      - URLS_LOGIN=http://localhost:4100/login
      - URLS_LOGOUT=http://localhost:4100/logout
      - URLS_SELF_ISSUER=http://localhost:4444
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-hydra-migrate-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-hydra-migrate
