version: '3'

services:
  web:
    image: reactioncommerce/example-storefront:4.0.2
    env_file:
      - ./web.env
    ports:
      - 4000:4000
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-web-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-web

  reaction-admin:
    image: reactioncommerce/admin:3.0.0-beta.13
    env_file:
      - ./reaction-admin.env
    ports:
      - "4080:4080"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-admin-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-admin

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db
    healthcheck:
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-mongo-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-mongo

  api:
    image: reactioncommerce/reaction:3.11.1
    environment:
      - MONGO_URL=mongodb://localhost:27017/reaction
      - ROOT_URL=http://localhost:3000
      - STRIPE_API_KEY=YOUR_PRIVATE_STRIPE_API_KEY      
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-api-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-api

  identity:
    image: reactioncommerce/identity:3.3.0
    env_file:
      - ./reaction-identity.env
    ports:
      - "4100:4100"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-identity-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-identity

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-postgres-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-postgres

volumes:
  mongo-db4:
  postgres-data:
