version: '3'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      default:
      reaction:
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-postgres-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-postgres

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db
    healthcheck:
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
    networks:
      default:
      reaction:
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-mongo-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-mongo

volumes:
  mongo-db4:
  postgres-data: