# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: "3"

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  api:
    image: public.ecr.aws/i8a0p2p6/reaction-api:latest
    environment:
      - MONGO_URL=mongodb://34.245.52.246:27017/reaction
      - ROOT_URL=http://localhost:3000
      - STRIPE_API_KEY=YOUR_PRIVATE_STRIPE_API_KEY
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: reaction-api-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: reaction-api


